Corrected the datatype of DoubleRange
Without this change, Elasticsearch will return the following exception:

elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'No handler for type [double_ranged] declared on field [my_range]’)

This is because according to the documentation, this datatype is actually called `double_range` not `double_ranged`. See: https://www.elastic.co/guide/en/elasticsearch/reference/current/range.html